name: Python Package using Conda

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente
  pull_request:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: '3.10'
          activate-environment: chess-env

      - name: Install dependencies
        run: |
          conda install -c conda-forge pygame flake8

      - name: Lint with flake8
        run: |
          source $(conda info --base)/condabin/activate chess-env
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


      - name: Run unit tests with unittest
        run: |
          cd Chess1.0.1/Chess
          python -m unittest discover -s tests -p 'utest_*.py'
