name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2  # Use pre-configured action
        with:
          miniconda-version: 'latest'  # Get the latest Miniconda
          python-version: '3.10'  # Specify Python version based on environment.yml
          activate-environment: 'chess-env'  # Activate environment after creation

      - name: Run unit tests with unittest
        run: |
          cd Chess1.0.1/Chess
          pwd  # Print working directory
          python -m unittest discover -s tests -p 'utest_*.py'


