name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          python-version: '3.10'
          activate-environment: 'chess-env'

      - name: Install Pygame (within Conda environment)
        run: conda install -c conda-forge pygame

      - name: Add Conda Environment PATH (Optional)
        run: |
        echo "source /usr/share/miniconda3/bin/activate chess-env" >> $GITHUB_PATH  # Replace with your environment activation command

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with unittest
        run: |
          cd Chess1.0.1/Chess
          python -m unittest discover -s tests -p 'utest_*.py'

      - name: Check for errors in test output
        run: if [ -z "$(grep -E 'ERROR|FAILED' < tests/output.txt)" ]; then echo "Tests passed without errors"; else exit 1; fi

      - name: Save test output
        run: python -m unittest discover -s tests -p 'utest_*.py' > tests/output.txt
