name: Run Tests

on:
  push:
    branches:
      - main  # Ajusta la rama según tu configuración
  pull_request:
    branches:
      - main  # Ajusta la rama según tu configuración

jobs:
  test:
    runs-on: ubuntu-latest  # Puedes ajustar el sistema operativo según tus necesidades

    steps:
    - uses: actions/checkout@v2  # Paso para clonar el repositorio

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ajusta según tus requisitos de instalación

    - name: Run tests
      run: |
        cd Chess1.0.1/Chess/tests
        # Ajusta el comando de acuerdo a tu entorno y lenguaje de programación
        # Por ejemplo, para Python y pytest:
        python -m unittest discover -s tests -p 'utest_*.py'