name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        cd Chess1.0.1/Chess/tests
        echo "flask==2.0.1" > requirements.txt
        echo "pytest==6.2.4" >> requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd Chess1.0.1/Chess/tests
        # Ajusta el comando de acuerdo a tu entorno y lenguaje de programación
        # Por ejemplo, para Python y pytest:
        pytest
